[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# For React SPA routing: fixes 404 on page refresh/deep links
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
